### PR TITLE
Refactor for Python 3 compatibility

### PR DESCRIPTION
**Pull request by kizniche**
Reference #8. I needed to use this with Python 3.5, so I refactored the code for it to work with both Python 2 and 3. I've tested these edits to work with the SHT75 with Python 2.7 and 3.5. I also edited setup.sh to include the new Python version. Could we see these edits incorporated to allow Python 3 support?

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks!

**Comment by mk-fg** [comment]
Do you mind if I'll add you as a comitter to this repo, so you can just test/fix stuff without asking me?
As also mentioned in #8, can't really test or do much about this thing myself these days.

I'd also like to transfer PyPI listing to you, but not sure how to do that properly yet... gotta look into it.

**Comment by kizniche** [comment]
Sure. I'm not familiar with PyPi, so I'm not sure if I edited the setup.py correctly.

**Comment by mk-fg** [comment]
Added.
Though guess even better option would be you maintaining fork on your gh/org as a proper owner, and this one linking to it in the README instead.

**Comment by kizniche** [comment]
If you think that's the best option, I'm fine with doing that. What would be required on my end to have any changes reflected in PyPi?

**Comment by mk-fg** [comment]
Basically you'd need to update the version field in setup.py and run `git push && python setup.py sdist bdist_wheel upload` every once in a while.
That will upload new package and update all metadata according to setup.py and README.rst.

For that to work, you'd also need to do two hopefully-trivial steps:
- Register on pypi.python.org and tell me your id (login) there (mine is mk.fg), so that I can add it as project owner for sht-sensor.
- Create ~/.pypirc with contents like following:
    ```
    [pypi]
    username: mk.fg
    password: ...
    ```
    So that `python setup.py upload` as suggested above will work without any extra prompting, and know who you are.
    Fairly sure that ~/.pypirc is created automatically first time you'd try to upload stuff and enter your creds though (and maybe stores API token these days not plaintext password), so maybe don't even need that.

**Comment by mk-fg** [comment]
Btw, to avoid bothering to update versions in setup.py by hand, I use this old script as git pre-commit hook (i.e. symlinked to .git/hooks/pre-commit) - https://github.com/mk-fg/fgtk/blob/master/dev/distribute_regen (does a bit more than that such version bumps though)
So if you'd have no dedicated release branches/points, can probably also use something similar to streamline "git push && setup.py upload" even more.

**Comment by mk-fg** [comment]
Two extra PyPI-related step in addition to two listed above that came to mind:

- Before pushing first new py3-compatible version to PyPI, grep for mk-fg in the code/README and update all these links to your (now main) fork.

- After pushing that first version, maybe update README.rst here to say that this fork is no longer maintained at the very top in bold/caps, though I can probably do that too, unless I'll forget.

**Comment by kizniche** [comment]
I'm kizniche on PyPi. Thanks for all the help and explaining that. I really appreciate it. I'm just glad you responded at all, but this is beyond great.

**Comment by mk-fg** [comment]
Added you there as "Owner" role ("Can upload releases. Can add other collaborators. Can delete files, releases, or the entire project"), good luck!
Hopefully it'd be rather easy for you to maintain this thing though, as not like these hardware sensors gonna change how they work anytime soon :)

**Comment by mk-fg** [comment]
Btw, PyPI project page: https://pypi.python.org/pypi/sht-sensor

**Comment by kizniche** [comment]
Thanks for everything. I'll take good care of the project :)

**Comment by mk-fg** [comment]
One other minor thing that just came to mind:

Once I've merged this PR few dozen minutes ago, I comitted a version bump then ran upload (way too) hastily, then looked at the PR/comments more closely and realized that maybe you didn't test it, and it might break stuff if anyone else uses the package.
So quickly went to pypi and deleted that latest release before anyone could download it.

And iirc pypi doesn't allow re-uploading different files with same version in them ever, so if you'll try to run upload without bumping the current version in setup.py and get some non-descriptive "403" or "version conflict" error back, be sure to update that number and it should work fine.

Thought it might be a bit confusing if I don't mention this.

**Comment by kizniche** [comment]
Thanks. I came to that exact conclusion [moments ago](https://github.com/kizniche/sht-sensor/commit/e6d1f08c38a069077114e278348968742676045b) :)

**Comment by kizniche** [comment]
Did you say you were you going to change your README to point to my repo? Just checking, because that sounded like a good idea to avoid confusion.

**Comment by mk-fg** [comment]
Ah yeah, sure, will do in a moment.
Thought you might beat me to it if you'll be uploading first release sometime later in the future and just wouldn't be able to notice, but should definitely be easy to do right now, keeping this repo only for py2.7 or historical issues' discussion, I guess.

**Comment by mk-fg** [comment]
Done, should probably be prominent enough in repo description, README header and in place of the Installation section.

There're also two ways to un-fork kizniche/sht-sensor - either by rebasing this/new repo on new "root" commit, or sending github a note to do it (e.g. dracut-crypt-ssh/dracut-crypt-ssh did that to "unfork" from mk-fg/dracut-crypt-sshd, I think for google-ability reasons).

You can probably do former one in a new repo (without any bad consequences, as there're probably no pulls from it yet), so it wouldn't be listed as a "fork", but dunno if it's worth breaking github fork-tree over that, and not entirely sure if it still works that way.

**Comment by mk-fg** [comment]
Apologies if it's a bother at this point, but noticed another minor quirk in setup.py that I forgot to mention and you might want to address:
- Add/put your name/email (email is definitely optional!) to either author/author_email or maintainer/maintainer_email fields - https://docs.python.org/distutils/setupscript.html#additional-meta-data

**Comment by kizniche** [comment]
Can their be both an author and maintainer, or only one?

**Comment by mk-fg** [comment]
Pretty sure it can both and it can be either, and pypi only checks for something to be in one of either fields.

**Comment by kizniche** [comment]
Haha. After adding just maintainer, it's now showing my name as a link to your email on PyPi. I guess I'll remove your email address.

**Comment by mk-fg** [comment]
Yeah, it'd probably be right thing to do too, as I'm not really one who should be there :)
Feel free to replace author/license stuff too - don't mind at all and pretty sure current license totally allows that.

**Comment by mk-fg** [comment]
Also, as pypi is definitely working for you, maybe you can remove me from Owners of sht-sensor there?
"Remove" button doesn't light up for removing myself, but maybe would work if you'd do it.
Reason is simply so that in case something happens to my acc there (e.g. compromise), it won't hurt projects that I don't need and shouldn't really have access to anymore.

**Comment by kizniche** [comment]
Okay. I removed you as owner. I'll finish the rest of the smaller stuff tomorrow. Thanks for everything.

**Pull request merged**
